### ISSUE TITLE
Show Humidity

### ISSUE THREAD

**Issue by ironhacker** [thevoltagesource/LennoxiComfort#17]
This component is working very well for me and I have multiple systems and zones!  I find the HA interface to better than the iComfort app, for the most part.  I see the API reports humidity, but I don't know how to expose this through HA.  It's not shown in the thermostat UI element or any other element I've tried.  Is this a limitation in HA and if so is there a straight forward way to to expose this attribute already defined in the component?  Thanks.

**Comment by thevoltagesource** [comment]
The humidity is exposed to HA as an attribute of the climate device but since the device doesn't support set_humdity, most of the thermostat cards won't display it.  I used a value template to capture the humidity and make it accessible as a sensor.  I use  [Simple Thermostat](https://github.com/nervetattoo/simple-thermostat) which allows me to add other sensors to the card.

To make the sensor I used the following code. My climate device is named 'lennox' and the resulting sensor is 'lennox_humidity'.

```
platform: template
sensors:
  lennox_humidity:
    value_template: "{{states.climate.lennox.attributes.current_humidity | float}}"
    friendly_name: "Humidity"
    unit_of_measurement: '%'
```

**Comment by ironhacker** [comment]
Thank you. Works great!

**Comment by theschles** [comment]
Hi @thevoltagesource @putz612 @ironhacker 

Brand new install of Home Assistant, never used it before.

I cannot figure out how to add the humidity config to my `configuration.yaml`.  Here's what I've done:

```
climate:
  - platform: myicomfort
    name: lennox
    username: !secret myicomfort_username
    password: !secret myicomfort_password
    system: 0
    zone: 0
    min_temp: 55
    max_temp: 90
    cloud_svc: lennox
  - platform: template
    sensors:
      lennox_humidity:
        value_template: "{{states.climate.lennox.attributes.current_humidity | float}}"
        friendly_name: "Humidity"
        unit_of_measurement: '%'
```

Result when I check configuration: `Platform error climate.template - No module named 'homeassistant.components.template.climate'`

If I try putting it at the left edge of the `configuration.yaml` file, e.g.:

```
climate:
  - platform: myicomfort
    name: lennox
    username: !secret myicomfort_username
    password: !secret myicomfort_password
    system: 0
    zone: 0
    min_temp: 55
    max_temp: 90
    cloud_svc: lennox
platform: template
sensors:
  lennox_humidity:
    value_template: "{{states.climate.lennox.attributes.current_humidity | float}}"
    friendly_name: "Humidity"
    unit_of_measurement: '%'
```

Result: `Integration error: platform - Integration 'platform' not found. Integration error: sensors - Integration 'sensors' not found.`

Help?

**Comment by thevoltagesource** [comment]
Oh yeah, HA changed the way they did template sensors and I haven't updated the readme to reflect that change.   Here is what you should use:

```
template:
  - sensor:
    - name: lennox_humidity
      unit_of_measurement: '%'
      state: '{{ states.climate.lennox.attributes.current_humidity | float }}'
```

I'll get the documentation updated.

**Comment by theschles** [comment]
Hi @thevoltagesource so good news / bad news:
* GOOD: The config you suggested above seems to work: I get a humidity reading if I go into the vertical-ellipsis for the thermostat card: 
<img width="541" alt="image" src="https://github.com/thevoltagesource/LennoxiComfort/assets/901430/3ce3fcab-49f6-4e2e-9ef5-e0fe2a0340ab">

* BAD: I can't seem to view the entity's value by itself:
<img width="471" alt="image" src="https://github.com/thevoltagesource/LennoxiComfort/assets/901430/42c1b6fe-abd4-4fba-b250-2a3e27a8660c">

What am I doing wrong?

**Comment by thevoltagesource** [comment]
Two ideas both in the developer tools section.  If you go to states and type `climate.lennox` into the filter, do you see your thermostat and does it show a value for `current_humidity` in the attributes?  Assuming you see those items, switch to the templates section and past this in to the editor `{{ states.climate.lennox.attributes.current_humidity | float }}`. Do you get a value in the results?   If all of those work, then it is probably a YAML spacing issue.

**Comment by theschles** [comment]
<img width="968" alt="image" src="https://github.com/thevoltagesource/LennoxiComfort/assets/901430/ab89dba8-2217-4caa-81db-fb24bd8eb534">

That was the trick!  See above.  I changed the configuration.yaml line from:
```
      state: '{{ states.climate.lennox.attributes.current_humidity | float }}'
```

to:

```
      state: '{{ states.climate.downstairs.attributes.current_humidity | float }}'
```



For reference, the full relevant section of `configuration.yaml`:

```
climate:
  - platform: myicomfort
    name: lennox
    username: !secret myicomfort_username
    password: !secret myicomfort_password
    system: 0
    zone: 0
    min_temp: 55
    max_temp: 90
    cloud_svc: lennox
template:
  - sensor:
    - name: lennox_humidity
      unit_of_measurement: '%'
      state: '{{ states.climate.downstairs.attributes.current_humidity | float }}'
```


Not sure where I configured `climate` to be `downstairs` -- but apparently I did...
